### ISSUE TITLE
Scanner/Review page  design

### ISSUE THREAD

**Issue by HugeLetters** [HugeLetters/recallio#19]
- [x] Кнопка скана штрих-кода и фрейм с выводом камеры.
- [x] После успешного скана 
  - [x] Если по коду найден прошлый отзыв пользователя, то юзера отображается его отзыв о продукте с возможностью перейти на отдельную страницу продукта.
- [x] Если нет - предлагается либо выбрать товары, найденные по этому коду(если такие есть), либо ввести название самостоятельно
- [x] После юзер вводит свою оценку и рецензию.

**Comment by AzaliiaKham** [comment]
![image](https://github.com/HugeLetters/recallio/assets/141032259/4abf1ff4-ea49-447d-bd82-55ac05642660)
![image](https://github.com/HugeLetters/recallio/assets/141032259/15f8617e-6934-4fde-b8fb-bb93678b9318)
![image](https://github.com/HugeLetters/recallio/assets/141032259/bc7ae04b-70e7-4239-af0f-d31e125bb2ef)

**Comment by AzaliiaKham** [comment]
поняла, по скидке в магните это тип пример комментария если шо
 ))

**Comment by HugeLetters** [comment]
> поняла, по скидке в магните это тип пример комментария если шо ))

Ааа, все, понял-понял, оке
