### ISSUE TITLE
Product page design

### ISSUE THREAD

**Issue by HugeLetters** [HugeLetters/recallio#20]
- [ ] Отображается личный отзыв юзера
- [ ] Отображаются публичные отзывы других пользователей с указанием названия продукта, которое они указали - какой-то достоверной БД, где есть по штрих-коду можно узнать точное название товара, не существует, так что названия для одного кода могут отличаться от юзера к юзеру. 
- [ ] Отображается сводная информация по товару, если такая есть - средняя оценка, количество отзывов, "официальное" название продукта, если такое получилось узнать
- [ ] Учесть, что у продукта в принципе может не быть никаких отзывов

**Comment by AzaliiaKham** [comment]
![image](https://github.com/HugeLetters/recallio/assets/141032259/cc6196e3-173d-4874-b0db-c8a20fc12555)
![image](https://github.com/HugeLetters/recallio/assets/141032259/6ef32e5f-954f-4e96-9a94-c95a9edb2e83)

**Comment by HugeLetters** [comment]
> 

1) - Про продукт достоверно известен только его штрих-код. 
   - Название - только ЕСЛИ повезет его с какой-то чужой БД вытащить, что вообще не гарантированно. Если отображать пользовательские названия, то у двух людей может быть разное мнение как товар называется - потому я и предложил в изначальном посте у каждого отзыва публичного отдельно отображать с каким названием он был запосчен. 
    - Страна, состав, категория - только если это будут заполнять юзеры сами, а поскольку инфа общая для всех, то это какая-то модерация нужна, и такой функционал пока точно не планируется
2. В первую очередь должно быть видно личный отзыв пользователя, который он оставлял сам, если такой есть - чужие отзывы и тп уже дальше.
3. Добавить в избранное/шейр - мне кажется, лишнее. Я не оч понимаю контекст, в котором этим будут пользоваться.
4. Я бы не перегружал отзывы списками, плюсами/минусами - это в первую очередь заметки для самого себя. 
5. Feed, Search, History - Фид я вообще не понимаю, что из себя может представлять в таком приложении)) Поиск смысла не имеет, если уже есть скан по коду. Историю просмотров - нууу, можно запилить в принципе

**Comment by AzaliiaKham** [comment]
навигацию такую дефолтную сделала, потому что пока не поняла как сделать, подредачу еще конечно
