### ISSUE TITLE
Profile page design

### ISSUE THREAD

**Issue by HugeLetters** [HugeLetters/recallio#21]
- [ ] Список отзывов пользователя с возможностью:
  - [ ] Сортировки по оценкам
  - [ ] Фильтрации по содержанию

**Comment by AzaliiaKham** [comment]
![image](https://github.com/HugeLetters/recallio/assets/141032259/dbf1b408-d5de-4045-b87f-d484d5f06c80)

**Comment by HugeLetters** [comment]
Гуд
