### ISSUE TITLE
Страница логина

### ISSUE THREAD

**Issue by HugeLetters** [HugeLetters/recallio#25]
### Варианты логина
- [ ] Через имейл(волшебная ссылка)
- [ ] Github
- [ ] Google
- [ ] Discord
- [ ] Facebook
- [ ] LinkedIn
- [ ] Twitter
- [ ] Telegram - под вопросом
- [ ] Имейл/Пароль - под вопросом

### Прочее
- [ ] Вывод ошибок в случае неудачного логина

**Comment by AzaliiaKham** [comment]
![image](https://github.com/HugeLetters/recallio/assets/141032259/5b6c957c-e184-43a7-a3e6-193b199072da)

**Comment by HugeLetters** [comment]
> <img alt="" height="700" src="https://user-images.githubusercontent.com/141032259/262121178-5b6c957c-e184-43a7-a3e6-193b199072da.png">

Мне нравится! Цветовая схема такая и будет? Я так-то не против, если ты захочешь какой-нибудь красочный/яркий/необычный дизайн запилить.
Можешь, кстати, сразу на фреймы из фигмы ссылки кидать тож

**Comment by AzaliiaKham** [comment]
Не, это еще только вайрфреймы, дизайн на следующем этапе
